hostname: irc.server.tld
ssl: off
ignoreMOTD: on
port: 6667
nick: DemonReach
username: DemonReach
realname: DemonReach
oper:
    username: opername
    password: operpass
channels:
    - #demonreach
    - #anope
